// Card-sized zombie-hand icon assets for small UI usage (~72-96px displayed).
//
// These are DISTINCT from the large interactive hands in src/data/hands.ts
// (which are 720px/1440px, used by <ZombieHand> for the homepage's bleeding-
// off-edge interactive art). This set is for compact card icons only.
//
// Generated by scripts/make-hand-cards.py (NOT scripts/optimize-hands.mjs):
//   - Source: the raw white-background PNGs in "Marketing Assets/Zombie Hands/"
//     (outside this repo).
//   - Background removed with rembg (isnet-general-use model), then trimmed to
//     the alpha bounding box — same trim convention as optimize-hands.mjs.
//   - CROPPED TO THE GESTURE. This is the step that matters: the source renders
//     are mostly forearm, so a plain full-arm trim leaves the actual hand only a
//     few pixels wide at card size. Each entry declares which end of the arm the
//     hand is on and how much of the long edge to keep.
//   - Resized so the longest edge is 192px (1x) / 384px (2x), LANCZOS, alpha
//     preserved; encoded WebP q82 / alpha_quality 90. Every 1x is under 10KB and
//     every 2x under 30KB.
//
// Re-run the script if the source gestures or crops change, then update the
// numbers below to whatever it prints — they are measured off the produced
// files, never guessed (zero-CLS rule, same as hands.ts).

export interface HandCardAsset {
  /** Stable slug id, e.g. "zh22-beckon". */
  id: string;
  /** 1x WebP path (longest edge 192px). */
  src: string;
  /** 2x WebP path (longest edge 384px), used for srcSet. */
  src2x: string;
  /** Intrinsic pixel width of the 1x asset. */
  width: number;
  /** Intrinsic pixel height of the 1x asset. */
  height: number;
  /** width / height, precomputed. */
  aspectRatio: number;
  /** Short human description of the gesture, e.g. "Beckoning hand". */
  label: string;
}

export const HAND_CARDS: Record<string, HandCardAsset> = {
  "zh22-beckon": {
    id: "zh22-beckon",
    src: "/hands/cards/zh22-beckon.webp",
    src2x: "/hands/cards/zh22-beckon@2x.webp",
    width: 192,
    height: 163,
    aspectRatio: 1.1779,
    label: "Beckoning hand",
  },
  "zh30-chefs-kiss": {
    id: "zh30-chefs-kiss",
    src: "/hands/cards/zh30-chefs-kiss.webp",
    src2x: "/hands/cards/zh30-chefs-kiss@2x.webp",
    width: 188,
    height: 192,
    aspectRatio: 0.9792,
    label: "Chef's kiss hand",
  },
  "zh06-ok-sign": {
    id: "zh06-ok-sign",
    src: "/hands/cards/zh06-ok-sign.webp",
    src2x: "/hands/cards/zh06-ok-sign@2x.webp",
    width: 165,
    height: 192,
    aspectRatio: 0.8594,
    label: "OK sign hand",
  },
  "zh08-highfive": {
    id: "zh08-highfive",
    src: "/hands/cards/zh08-highfive.webp",
    src2x: "/hands/cards/zh08-highfive@2x.webp",
    width: 133,
    height: 192,
    aspectRatio: 0.6927,
    label: "High five hand",
  },
};

export type HandCardId = keyof typeof HAND_CARDS;
