// AUTO-GENERATED by scripts/optimize-hands.mjs — do not edit by hand.
// Intrinsic dimensions of the optimized 1x WebP hands, so every <ZombieHand>
// can set width/height and contribute ZERO cumulative layout shift.

export interface HandAsset {
  /** Stable slug id, e.g. "zh09-thumbsdown-l". */
  id: string;
  /** 1x WebP path (longest edge 720px). */
  src: string;
  /** 2x WebP path (longest edge 1440px), used for srcSet. */
  src2x: string;
  /** Intrinsic pixel width of the 1x asset. */
  width: number;
  /** Intrinsic pixel height of the 1x asset. */
  height: number;
  /** width / height, precomputed. */
  aspectRatio: number;
}

export const HANDS: Record<string, HandAsset> = {
  "zh01-thumbsup-l": {
    id: "zh01-thumbsup-l",
    src: "/hands/zh01-thumbsup-l.webp",
    src2x: "/hands/zh01-thumbsup-l@2x.webp",
    width: 720,
    height: 392,
    aspectRatio: 1.8367,
  },
  "zh09-thumbsdown-l": {
    id: "zh09-thumbsdown-l",
    src: "/hands/zh09-thumbsdown-l.webp",
    src2x: "/hands/zh09-thumbsdown-l@2x.webp",
    width: 720,
    height: 462,
    aspectRatio: 1.5584,
  },
  "zh10-rockon-r": {
    id: "zh10-rockon-r",
    src: "/hands/zh10-rockon-r.webp",
    src2x: "/hands/zh10-rockon-r@2x.webp",
    width: 352,
    height: 720,
    aspectRatio: 0.4889,
  },
  "zh11-point-up": {
    id: "zh11-point-up",
    src: "/hands/zh11-point-up.webp",
    src2x: "/hands/zh11-point-up@2x.webp",
    width: 234,
    height: 720,
    aspectRatio: 0.3250,
  },
  "zh25-point-diag": {
    id: "zh25-point-diag",
    src: "/hands/zh25-point-diag.webp",
    src2x: "/hands/zh25-point-diag@2x.webp",
    width: 658,
    height: 720,
    aspectRatio: 0.9139,
  },
  "zh34-highfive-l": {
    id: "zh34-highfive-l",
    src: "/hands/zh34-highfive-l.webp",
    src2x: "/hands/zh34-highfive-l@2x.webp",
    width: 720,
    height: 358,
    aspectRatio: 2.0112,
  },
  "zh37-thumbsup-r": {
    id: "zh37-thumbsup-r",
    src: "/hands/zh37-thumbsup-r.webp",
    src2x: "/hands/zh37-thumbsup-r@2x.webp",
    width: 720,
    height: 371,
    aspectRatio: 1.9407,
  },
};

export type HandId = keyof typeof HANDS;
